<?php

namespace App\Enum;

interface District {

    const List = [
        /* 'dhaka' => 'Dhaka',
        'chittagong' => 'Chittagong',
        'rajshahi' => 'Rajshahi',
        'khulna' => 'Khulna',
        'barisal' => 'Barisal',
        'sylhet' => 'Sylhet',
        'mymensingh' => 'Mymensingh',
        'rangpur' => 'Rangpur', */
        'barguna' => 'Barguna',
        'barisal'=>'Barisal',
        'bhola' => 'Bhola',
        'jhalokati' => 'Jhalokati',
        'patuakhali'=>'Patuakhali',
        'pirojpur' => 'Pirojpur',
        'bandarban' => 'Bandarban',
        'brahmanbaria'=>'Brahmanbaria',
        'chandpur' => 'Chandpur',
        'chittagong' => 'Chittagong',
        'comilla'=>'Comilla',
        "cox's Bazar" => "Cox's Bazar",
        'feni' => 'Feni',
        'khagrachhari'=>'Khagrachhari',
        'lakshmipur' => 'Lakshmipur',
        'noakhali' => 'Noakhali',
        'rangamati'=>'Rangamati',
        'dhaka' => 'Dhaka',
        'faridpur' => 'Faridpur',
        'gazipur'=>'Gazipur',
        'gopalganj' => 'Gopalganj',
        'kishoreganj' => 'Kishoreganj',
        'madaripur'=>'Madaripur',
        'manikganj' => 'Manikganj',
        'munshiganj' => 'Munshiganj',
        'narayanganj'=>'Narayanganj',
        'narsingdi' => 'Narsingdi',
        'rajbari' => 'Rajbari',
        'shariatpur'=>'Shariatpur',
        'tangail' => 'Tangail',
        'bagerhat' => 'Bagerhat',
        'chuadanga'=>'Chuadanga',
        'jessore' => 'Jessore',
        'jhenaidah' => 'Jhenaidah',
        'khulna'=>'Khulna',
        'kushtia' => 'Kushtia',
        'magura' => 'Magura',
        'meherpur'=>'Meherpur',
        'narail' => 'Narail',
        'satkhira' => 'Satkhira',
        'jamalpur'=>'Jamalpur',
        'mymensingh' => 'Mymensingh',
        'netrokona' => 'Netrokona',
        'sherpur'=>'Sherpur',
        'bogra' => 'Bogra',
        'joypurhat' => 'Joypurhat',
        'naogaon'=>'Naogaon',
        'natore' => 'Natore',
        'chapai nawabganj' => 'Chapai Nawabganj',
        'pabna'=>'Pabna',
        'rajshahi' => 'Rajshahi',
        'sirajganj' => 'Sirajganj',
        'dinajpur'=>'Dinajpur',
        'gaibandha' => 'Gaibandha',
        'kurigram' => 'Kurigram',
        'lalmonirhat'=>'Lalmonirhat',
        'nilphamari' => 'Nilphamari',
        'panchagarh' => 'Panchagarh',
        'rangpur'=>'Rangpur',
        'thakurgaon' => 'Thakurgaon',
        'habiganj' => 'Habiganj',
        'moulvibazar' => 'Moulvibazar',
        'sunamganj'=>'Sunamganj',
        'sylhet' => 'Sylhet',


    ];
}
